### ISSUE TITLE
[Bug]: 请适配LL3 0.13.5&BDS 1.21.3

### ISSUE THREAD

**Issue by BensonChen2456** [yhzx233/FixChunkLeak#2]
### Describe the bug

请适配LL3 0.13.5&BDS 1.21.3 无法运行在此版本上

### To Reproduce

![image](https://github.com/user-attachments/assets/f4a4d69d-78e5-4a7f-8a4c-d67bdb2e5c6d)

### Expected behavior

请适配LL3 0.13.5&BDS 1.21.3 无法运行在此版本上
将插件放入plugins文件夹 无法运行

### Screenshots

请适配LL3 0.13.5&BDS 1.21.3 无法运行在此版本上
![image](https://github.com/user-attachments/assets/f4a4d69d-78e5-4a7f-8a4c-d67bdb2e5c6d)

### Platform

Windows Sever 2016

### BDS Version

1.21.3

### LeviLamina Version

0.13.5

### Version

0.5.1(Latest)

### Additional context

![image](https://github.com/user-attachments/assets/f4a4d69d-78e5-4a7f-8a4c-d67bdb2e5c6d)

**Comment by yhzx233** [comment]
本插件功能已经集成到 https://github.com/LiteLDev/LeviOptimize
